name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
          version: 13
          platform: x64
    - uses: actions/checkout@v3
    - name: Install rustc 1.59.0
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.59.0
          override: true
          
      
    - uses: rui314/setup-mold@v1
    
    - name: Run cargo build
      run: cd back && cargo build --release --verbose
