name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
defaults:
  run:
    working-directory: ./back
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install rustc 1.59.0
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.59.0
          override: true
          
      
    - uses: rui314/setup-mold@v1
    
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
          command: build --verbose
